server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: USERS
          predicates:
            - Path=/user/**
          uri: lb://users
          filters:
            - GatewayAuthFilter

