server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: USERS
          predicates:
            - Path=/user/**
          uri: lb://users
          filters:
            - GatewayAuthFilter
        - id: PROBLEM
          predicates:
            - Path=/problem/**
          uri: lb://problem
          filters:
            - GatewayAuthFilter
        - id: SUBMISSION
          predicates:
            - Path=/submission/**
          uri: lb://submission
          filters:
            - GatewayAuthFilter
        - id: TEST
          predicates:
            - Path=/test/**
          uri: lb://test
        - id: CLAN
          predicates:
            - Path=/clan/**
          uri: lb://clan
          filters:
            - GatewayAuthFilter
        - id: NOTIFICATION
          predicates:
            - Path=/notification/**
          uri: lb://notification

