server:
  port: 8600
  servlet:
    context-path: /discussion
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
spring:
  application:
    name: discussion
  rabbitmq:
    host: 34.93.145.38
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hacknconquer_discussion
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://34.93.145.38:8888