server:
  port: 8400
  servlet:
    context-path: /submission
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: submission
  data:
    mongodb:
      uri: mongodb+srv://root:password7@hacknconquer-cluster.6hthxlx.mongodb.net/
      database: hacknconquer_submission
  config:
    import: optional:configserver:http://34.93.145.38:8888