server:
  port: 8100
  servlet:
    context-path: "/user"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: users
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hacknconquer_user?autoCreate=true
    username: root
    password: PasswordChanged@7
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8888
