server:
  port: 9800
  servlet:
    context-path: "/chat"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
spring:
  application:
    name: chat
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hacknconquer_chat
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://34.93.145.38:8888