server:
  port: 9800
  servlet:
    context-path: "/chat"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: chat
  zipkin:
    base-url: http://34.93.145.38:9411
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hacknconquer_chat?autoCreate=true
    username: root
    password: PasswordChanged@7
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8888