server:
  port: 9600
  servlet:
    context-path: "/clan"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: clan
  rabbitmq:
    host: 34.93.145.38
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/hacknconquer_clan?autoCreate=true
    username: root
    password: PasswordChanged@7
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8888
aws:
  access:
    key: AKIA5JPIHCOQZWFLMC5K
  s3:
    bucket: hacknconquer
  secret:
    key: MXlbs+3+EQFIrsi/vleMZ1svyTdxw80PKfB3hYN2