server:
  port: 8100
  servlet:
    context-path: "/user"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: problem
  
  config:
    import: optional:configserver:http://localhost:8888