server:
  port: 8200
  servlet:
    context-path: /problem
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: problem
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/
      database: hacknconquer_problem
  config:
    import: optional:configserver:http://localhost:8888