server:
  port: 8500
  servlet:
    context-path: /test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: test
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/
      database: hacknconquer_test
  config:
    import: optional:configserver:http://localhost:8888