server:
  port: 8500
  servlet:
    context-path: /test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
spring:
  application:
    name: test
  data:
    mongodb:
      uri: mongodb+srv://root:password7@hacknconquer-cluster.6hthxlx.mongodb.net/
      database: hacknconquer_test
  config:
    import: optional:configserver:http://34.93.145.38:8888