name: Build & Publish user service Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "user-service/**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./user-service/
          push: true
          tags: shamalmuneer/hacknconquer-user:latest
  deploy_to_gke:
    name: Deploy to Google Kubernetes Engine
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure kubectl
        run: |-
          gcloud container clusters get-credentials hacknconquer --region asia-south1 --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to GKE
        run: |-
          kubectl set image deployment/hacknconquer-user user-service=shamalmuneer/hacknconquer-user:latest
          kubectl rollout status deployment/hacknconquer-user